minecraft_version=26.1.2
minecraft_version_range=26.1.x
loader_version=0.19.3
loom_version=1.16-SNAPSHOT
fabric_api_version=0.155.2+26.1.2

mod_version=2.0.8
maven_group=de.chunkloader
archives_base_name=chunkloader

java_version=25

org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false
